name: Deploy Summarization Web Client

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'summarization_webclient/**'
      
env:
  STORAGE_ACCOUNT_NAME: 'millsumaiweb'
  ROOT_PATH: ./summarization_webclient

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
      
    - uses: actions/setup-node@v4
      with:
        node-version: 22
          
    - name: Build
      shell: bash
      run: |
        cd ${{env.ROOT_PATH}}
        npm install
        npm run build
        
    - name: Upload to Blob Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name ${{ env.STORAGE_ACCOUNT_NAME }} -d '$web' --account-key ${{ secrets.STATIC_WEBSITE_ACCESS_KEY }} -s ${{env.ROOT_PATH}}/dist
