name: Deploy Summarization Web Client

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'summarization_webclient/**'
      
env:
  STORAGE_ACCOUNT_NAME: 'millsumaiweb'

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
      
    - name: Stage Files
      shell: bash
      run: |
        mkdir ./output
        cp ./summarization_webclient/index.html ./output/
        
    - name: Upload to Blob Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name ${{ env.STORAGE_ACCOUNT_NAME }} -d '$web' --account-key ${{ secrets.STATIC_WEBSITE_ACCESS_KEY }} -s ./output
  
